name: ci
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: pnpm/action-setup@v3
        with:
          version: 9.4.0
      - name: Install dependencies
        run: pnpm install -r --no-frozen-lockfile --prefer-offline
      - name: Lint
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.4.0
      - name: Install dependencies
        run: pnpm install -r --no-frozen-lockfile --prefer-offline
      - name: Test
        run: pnpm run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.4.0
      - name: Install dependencies
        run: pnpm install -r --no-frozen-lockfile --prefer-offline
      - name: Cache Build Artifacts
        uses: actions/cache@v3
        with:
          path: ./dist
          key: ${{ runner.os }}-build-${{ hashFiles('src/**/*') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Build
        run: pnpm run build

